### ISSUE TITLE
Glass's icon

### ISSUE THREAD

**Issue by SkyWors** [Finoway/Glass#1]
Hey! 
I just want to submit a new icon for Glass's projects 

![Glass](https://user-images.githubusercontent.com/70440695/188269940-bda56cc6-d287-4e97-9566-ef5b6fef4271.png)

Have a nice day! :D

**Comment by SkyWors** [comment]
And now, banner!

![image189](https://user-images.githubusercontent.com/70440695/188271222-c1c4ffb8-69a8-4228-aa93-dfe3f45a511c.png)

**Comment by Finoway** [comment]
Hello, thanks for the icon and the banner.
I will add it in one of my future commit
